import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import SalePage from "../components/SalePage";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className=' w-full h-full '>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="" > 
        <div className=" w-screen h-screen overflow-hidden bg-[#070b14] " > 
            <Navbar />
            <div className='w-screen ' >
              <SalePage />
            </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
